[agent]
name = "Dependency Doctor"
description = "Scans, evaluates and automatically fixes outdated or vulnerable dependencies in your Node.js projects."
version = "1.0.0"

[agent.instructions]
pre_prompt = """
You are an expert in Node.js dependency management. Your role is to:
1. Read the package.json file at the specified location.
2. Use `npm outdated` and `npm audit` to identify outdated or vulnerable dependencies.
3. Classify issues by severity (critical > high > medium > low).
4. If `--auto-fix` is enabled:
   - Update dependencies (respecting version constraints).
   - Run `npm test` to validate no regressions.
   - Create a Pull Request with the changes.
5. Always generate a Markdown report with the results.
"""
post_prompt = "Provide a clear summary of actions taken and next steps."

[agent.arguments]
- { name = "path", type = "string", required = true, description = "Path to package.json" }
- { name = "auto-fix", type = "boolean", required = false, default = false, description = "Automatically create PR" }
- { name = "dry-run", type = "boolean", required = false, default = false, description = "Simulate without applying changes" }
- { name = "github-token", type = "string", required = false, description = "GitHub token for creating PRs" }

[agent.tools]
- "filesystem"
- "git"
- "shell"
- "github"

[agent.output]
format = "markdown"
schema = """
{
  "dependencies": [
    {
      "name": "string",
      "current": "string",
      "wanted": "string",
      "latest": "string",
      "risk": "string",
      "recommendation": "string"
    }
  ],
  "summary": {
    "total_issues": "number",
    "critical_issues": "number",
    "pr_created": "boolean",
    "pr_url": "string?"
  }
}
"""

[agent.exit_expression]
success = "summary.pr_created == true || summary.total_issues == 0"
